version: '3.8'

services:
  back:
    build:
      context: ./app
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
      - DATABASE_URL=sqlite:///app.db
    volumes:
      - ./app:/app
    command: >
      bash -c "flask db upgrade && flask db migrate -m 'Auto migration' && flask db upgrade && flask run --host=0.0.0.0"

  front:
    build:
      context: front
      dockerfile: docker/Dockerfile
    ports:
      - "3000:80"